apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: OnFailure
  runtimeClassName: seeweb-nvidia-1xa100 # runtimeClass to use
  containers:
  - name: nvidia
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["sleep 3600"]
    imagePullPolicy: Always
  tolerations:
  - key: "virtual-kubelet.io/provider"
    operator: "Equal"
    value: "k8sgpu"
    effect: "NoExecute"
